version: 2
jobs:
  build:
    working_directory: ~/cljsjs
    docker:
      - image: circleci/clojure:boot-2.7.2-node
    steps:
      - checkout
      # No easy way to create checksum for cljsjs
      - restore_cache:
          key: cljsjs-v3
      - restore_cache:
          key: closure-{{ checksum "test-extern-files.sh" }}
      - run: ./setup_gpg.sh
      - run: ./circle.sh
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: cljsjs-v3
      - save_cache:
          key: closure-{{ checksum "test-extern-files.sh" }}
          paths:
            - ~/cljsjs/closure-compiler.jar
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"
      NPM_CONFIG_LOGLEVEL: warn
      NPM_CONFIG_UNSAFE_PERMS: true
